#! /usr/bin/env ruby

#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.
#
#

limit = 4_000_000
terms = [1,2,3,5,8,13,21,34,55,89]

while true
  next_term = terms[terms.length - 2] + terms.last
  if next_term < limit
    terms << next_term
  else
    break
  end
end

puts terms.select{ |term| term.even? }.reduce(:+)
